// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MimeType      string                 `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	SizeBytes     int32                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_proto_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Image) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Image) GetSizeBytes() int32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Profile       *User_Profile          `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetProfile() *User_Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	To            *string                `protobuf:"bytes,4,opt,name=to,proto3,oneof" json:"to,omitempty"`
	Image         *Image                 `protobuf:"bytes,5,opt,name=image,proto3,oneof" json:"image,omitempty"`
	UnixTime      int64                  `protobuf:"varint,6,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	Private       bool                   `protobuf:"varint,7,opt,name=private,proto3" json:"private,omitempty"`
	SenderIcon    *Image                 `protobuf:"bytes,8,opt,name=sender_icon,json=senderIcon,proto3,oneof" json:"sender_icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChatMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetTo() string {
	if x != nil && x.To != nil {
		return *x.To
	}
	return ""
}

func (x *ChatMessage) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ChatMessage) GetUnixTime() int64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

func (x *ChatMessage) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *ChatMessage) GetSenderIcon() *Image {
	if x != nil {
		return x.SenderIcon
	}
	return nil
}

type JoinRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Icon           *Image                 `protobuf:"bytes,2,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	RequestHistory bool                   `protobuf:"varint,3,opt,name=request_history,json=requestHistory,proto3" json:"request_history,omitempty"`
	MaxHistory     int32                  `protobuf:"varint,4,opt,name=max_history,json=maxHistory,proto3" json:"max_history,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JoinRequest) GetIcon() *Image {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *JoinRequest) GetRequestHistory() bool {
	if x != nil {
		return x.RequestHistory
	}
	return false
}

func (x *JoinRequest) GetMaxHistory() int32 {
	if x != nil {
		return x.MaxHistory
	}
	return 0
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	To            *string                `protobuf:"bytes,2,opt,name=to,proto3,oneof" json:"to,omitempty"`
	Image         *Image                 `protobuf:"bytes,3,opt,name=image,proto3,oneof" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendMessageRequest) GetTo() string {
	if x != nil && x.To != nil {
		return *x.To
	}
	return ""
}

func (x *SendMessageRequest) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixTime      int64                  `protobuf:"varint,1,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{5}
}

func (x *PingRequest) GetUnixTime() int64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

type ClientRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ClientSeq int32                  `protobuf:"varint,1,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientRequest_Join
	//	*ClientRequest_Send
	//	*ClientRequest_Ping
	Payload       isClientRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_proto_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ClientRequest) GetClientSeq() int32 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

func (x *ClientRequest) GetPayload() isClientRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientRequest) GetJoin() *JoinRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientRequest_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *ClientRequest) GetSend() *SendMessageRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientRequest_Send); ok {
			return x.Send
		}
	}
	return nil
}

func (x *ClientRequest) GetPing() *PingRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientRequest_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isClientRequest_Payload interface {
	isClientRequest_Payload()
}

type ClientRequest_Join struct {
	Join *JoinRequest `protobuf:"bytes,2,opt,name=join,proto3,oneof"`
}

type ClientRequest_Send struct {
	Send *SendMessageRequest `protobuf:"bytes,3,opt,name=send,proto3,oneof"`
}

type ClientRequest_Ping struct {
	Ping *PingRequest `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

func (*ClientRequest_Join) isClientRequest_Payload() {}

func (*ClientRequest_Send) isClientRequest_Payload() {}

func (*ClientRequest_Ping) isClientRequest_Payload() {}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{7}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type History struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Images        []*Image               `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	LastImage     *Image                 `protobuf:"bytes,3,opt,name=last_image,json=lastImage,proto3,oneof" json:"last_image,omitempty"`
	Users         []*User                `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *History) Reset() {
	*x = History{}
	mi := &file_proto_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{8}
}

func (x *History) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *History) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *History) GetLastImage() *Image {
	if x != nil {
		return x.LastImage
	}
	return nil
}

func (x *History) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type ServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerSeq     int32                  `protobuf:"varint,1,opt,name=server_seq,json=serverSeq,proto3" json:"server_seq,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	History       *History               `protobuf:"bytes,4,opt,name=history,proto3,oneof" json:"history,omitempty"`
	Message       *ChatMessage           `protobuf:"bytes,5,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Info          string                 `protobuf:"bytes,6,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_proto_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ServerResponse) GetServerSeq() int32 {
	if x != nil {
		return x.ServerSeq
	}
	return 0
}

func (x *ServerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ServerResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ServerResponse) GetHistory() *History {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *ServerResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerResponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type User_Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Icon          *Image                 `protobuf:"bytes,1,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	HasIcon       bool                   `protobuf:"varint,2,opt,name=has_icon,json=hasIcon,proto3" json:"has_icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Profile) Reset() {
	*x = User_Profile{}
	mi := &file_proto_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Profile) ProtoMessage() {}

func (x *User_Profile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Profile.ProtoReflect.Descriptor instead.
func (*User_Profile) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{1, 0}
}

func (x *User_Profile) GetIcon() *Image {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *User_Profile) GetHasIcon() bool {
	if x != nil {
		return x.HasIcon
	}
	return false
}

var File_proto_chat_proto protoreflect.FileDescriptor

const file_proto_chat_proto_rawDesc = "" +
	"\n" +
	"\x10proto/chat.proto\x12\achat.v1\"W\n" +
	"\x05Image\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x05R\tsizeBytes\"\xa3\x01\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\aprofile\x18\x02 \x01(\v2\x15.chat.v1.User.ProfileR\aprofile\x1aV\n" +
	"\aProfile\x12'\n" +
	"\x04icon\x18\x01 \x01(\v2\x0e.chat.v1.ImageH\x00R\x04icon\x88\x01\x01\x12\x19\n" +
	"\bhas_icon\x18\x02 \x01(\bR\ahasIconB\a\n" +
	"\x05_icon\"\x93\x02\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x13\n" +
	"\x02to\x18\x04 \x01(\tH\x00R\x02to\x88\x01\x01\x12)\n" +
	"\x05image\x18\x05 \x01(\v2\x0e.chat.v1.ImageH\x01R\x05image\x88\x01\x01\x12\x1b\n" +
	"\tunix_time\x18\x06 \x01(\x03R\bunixTime\x12\x18\n" +
	"\aprivate\x18\a \x01(\bR\aprivate\x124\n" +
	"\vsender_icon\x18\b \x01(\v2\x0e.chat.v1.ImageH\x02R\n" +
	"senderIcon\x88\x01\x01B\x05\n" +
	"\x03_toB\b\n" +
	"\x06_imageB\x0e\n" +
	"\f_sender_icon\"\x9d\x01\n" +
	"\vJoinRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04icon\x18\x02 \x01(\v2\x0e.chat.v1.ImageH\x00R\x04icon\x88\x01\x01\x12'\n" +
	"\x0frequest_history\x18\x03 \x01(\bR\x0erequestHistory\x12\x1f\n" +
	"\vmax_history\x18\x04 \x01(\x05R\n" +
	"maxHistoryB\a\n" +
	"\x05_icon\"y\n" +
	"\x12SendMessageRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x13\n" +
	"\x02to\x18\x02 \x01(\tH\x00R\x02to\x88\x01\x01\x12)\n" +
	"\x05image\x18\x03 \x01(\v2\x0e.chat.v1.ImageH\x01R\x05image\x88\x01\x01B\x05\n" +
	"\x03_toB\b\n" +
	"\x06_image\"*\n" +
	"\vPingRequest\x12\x1b\n" +
	"\tunix_time\x18\x01 \x01(\x03R\bunixTime\"\xc4\x01\n" +
	"\rClientRequest\x12\x1d\n" +
	"\n" +
	"client_seq\x18\x01 \x01(\x05R\tclientSeq\x12*\n" +
	"\x04join\x18\x02 \x01(\v2\x14.chat.v1.JoinRequestH\x00R\x04join\x121\n" +
	"\x04send\x18\x03 \x01(\v2\x1b.chat.v1.SendMessageRequestH\x00R\x04send\x12*\n" +
	"\x04ping\x18\x04 \x01(\v2\x14.chat.v1.PingRequestH\x00R\x04pingB\t\n" +
	"\apayload\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcb\x01\n" +
	"\aHistory\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.chat.v1.ChatMessageR\bmessages\x12&\n" +
	"\x06images\x18\x02 \x03(\v2\x0e.chat.v1.ImageR\x06images\x122\n" +
	"\n" +
	"last_image\x18\x03 \x01(\v2\x0e.chat.v1.ImageH\x00R\tlastImage\x88\x01\x01\x12#\n" +
	"\x05users\x18\x04 \x03(\v2\r.chat.v1.UserR\x05usersB\r\n" +
	"\v_last_image\"\x86\x02\n" +
	"\x0eServerResponse\x12\x1d\n" +
	"\n" +
	"server_seq\x18\x01 \x01(\x05R\tserverSeq\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x0e.chat.v1.ErrorH\x00R\x05error\x88\x01\x01\x12/\n" +
	"\ahistory\x18\x04 \x01(\v2\x10.chat.v1.HistoryH\x01R\ahistory\x88\x01\x01\x123\n" +
	"\amessage\x18\x05 \x01(\v2\x14.chat.v1.ChatMessageH\x02R\amessage\x88\x01\x01\x12\x12\n" +
	"\x04info\x18\x06 \x01(\tR\x04infoB\b\n" +
	"\x06_errorB\n" +
	"\n" +
	"\b_historyB\n" +
	"\n" +
	"\b_messageB#Z!hw05chat/internal/protocol/chatpbb\x06proto3"

var (
	file_proto_chat_proto_rawDescOnce sync.Once
	file_proto_chat_proto_rawDescData []byte
)

func file_proto_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_proto_rawDesc), len(file_proto_chat_proto_rawDesc)))
	})
	return file_proto_chat_proto_rawDescData
}

var file_proto_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_chat_proto_goTypes = []any{
	(*Image)(nil),              // 0: chat.v1.Image
	(*User)(nil),               // 1: chat.v1.User
	(*ChatMessage)(nil),        // 2: chat.v1.ChatMessage
	(*JoinRequest)(nil),        // 3: chat.v1.JoinRequest
	(*SendMessageRequest)(nil), // 4: chat.v1.SendMessageRequest
	(*PingRequest)(nil),        // 5: chat.v1.PingRequest
	(*ClientRequest)(nil),      // 6: chat.v1.ClientRequest
	(*Error)(nil),              // 7: chat.v1.Error
	(*History)(nil),            // 8: chat.v1.History
	(*ServerResponse)(nil),     // 9: chat.v1.ServerResponse
	(*User_Profile)(nil),       // 10: chat.v1.User.Profile
}
var file_proto_chat_proto_depIdxs = []int32{
	10, // 0: chat.v1.User.profile:type_name -> chat.v1.User.Profile
	0,  // 1: chat.v1.ChatMessage.image:type_name -> chat.v1.Image
	0,  // 2: chat.v1.ChatMessage.sender_icon:type_name -> chat.v1.Image
	0,  // 3: chat.v1.JoinRequest.icon:type_name -> chat.v1.Image
	0,  // 4: chat.v1.SendMessageRequest.image:type_name -> chat.v1.Image
	3,  // 5: chat.v1.ClientRequest.join:type_name -> chat.v1.JoinRequest
	4,  // 6: chat.v1.ClientRequest.send:type_name -> chat.v1.SendMessageRequest
	5,  // 7: chat.v1.ClientRequest.ping:type_name -> chat.v1.PingRequest
	2,  // 8: chat.v1.History.messages:type_name -> chat.v1.ChatMessage
	0,  // 9: chat.v1.History.images:type_name -> chat.v1.Image
	0,  // 10: chat.v1.History.last_image:type_name -> chat.v1.Image
	1,  // 11: chat.v1.History.users:type_name -> chat.v1.User
	7,  // 12: chat.v1.ServerResponse.error:type_name -> chat.v1.Error
	8,  // 13: chat.v1.ServerResponse.history:type_name -> chat.v1.History
	2,  // 14: chat.v1.ServerResponse.message:type_name -> chat.v1.ChatMessage
	0,  // 15: chat.v1.User.Profile.icon:type_name -> chat.v1.Image
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_chat_proto_init() }
func file_proto_chat_proto_init() {
	if File_proto_chat_proto != nil {
		return
	}
	file_proto_chat_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_chat_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_chat_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_chat_proto_msgTypes[6].OneofWrappers = []any{
		(*ClientRequest_Join)(nil),
		(*ClientRequest_Send)(nil),
		(*ClientRequest_Ping)(nil),
	}
	file_proto_chat_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_chat_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_chat_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_proto_rawDesc), len(file_proto_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_proto_depIdxs,
		MessageInfos:      file_proto_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_proto = out.File
	file_proto_chat_proto_goTypes = nil
	file_proto_chat_proto_depIdxs = nil
}
